CREATE DATABASE IF NOT EXISTS MARKETING_DB;

CREATE SCHEMA IF NOT EXISTS MARKETING_DB.RAW;
CREATE SCHEMA IF NOT EXISTS MARKETING_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS MARKETING_DB.MART;
CREATE SCHEMA IF NOT EXISTS MARKETING_DB.INTERMEDIATE;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL',
    AUTO_SUSPEND = 60,
    AUTO_RESUME = TRUE;

USE WAREHOUSE COMPUTE_WH;
USE DATABASE MARKETING_DB;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

-- Create raw tables for ads campaigns, costs, and site revenue

CREATE OR REPLACE TABLE RAW_ADS_CAMPAIGNS (
    campaign_id STRING,
    campaign_name STRING,
    channel STRING,
    country STRING,
    start_date DATE,
    status STRING
);

CREATE OR REPLACE TABLE RAW_ADS_COSTS (
    date DATE,
    campaign_id STRING,
    impressions INT,
    clicks INT,
    cost FLOAT
);

CREATE OR REPLACE TABLE RAW_SITE_REVENUE (
    date DATE,
    campaign_id STRING,
    sessions INT,
    pageviews INT,
    revenue FLOAT
);

-- Create stage for raw marketing data

CREATE OR REPLACE STAGE S3_MARKETING_STAGE
URL = 's3://BUCKET/marketing_data/raw/'
CREDENTIALS = (
    AWS_KEY_ID = '<KEY>',
    AWS_SECRET_KEY = '<SECRET>'
)
FILE_FORMAT = CSV_FORMAT;